language: node_js
node_js:
  - "node"
before_install:
  - pip install --user codecov
after_success:
  - npm run coverage
  - codecov --file coverage/lcov.info --disable search
notifications:
  email:
    on_success: never
    on_failure: never
